# Generated by Django 4.2.1 on 2024-03-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_sch_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
