# Generated by Django 4.2.1 on 2024-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_std_sch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='std_sch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
