# Generated by Django 4.2.1 on 2024-03-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_remove_student_id_alter_student_std_sch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('school_year', models.CharField(help_text='Format: YYYY-YYYY, e.g., 2024-2025', max_length=9)),
                ('enrollment_number', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'unique_together': {('school_year', 'enrollment_number')},
            },
        ),
    ]
