# Generated by Django 4.2.1 on 2024-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
