# Generated by Django 4.2.1 on 2024-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the subject, e.g., MATH101', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Name of the subject, e.g., Mathematics', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the subject')),
                ('credits', models.PositiveIntegerField(help_text='Number of credits for the subject')),
            ],
        ),
    ]
