# Generated by Django 4.2.1 on 2024-03-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(help_text='The start year of the school year, e.g., 2024')),
                ('end_year', models.PositiveSmallIntegerField(help_text='The end year of the school year, e.g., 2025')),
                ('is_current', models.BooleanField(default=False, help_text='Indicates if this is the current school year')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollment.schoolyear'),
        ),
    ]
