# Generated by Django 4.2.1 on 2024-03-06 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_schoolyear_alter_enrollment_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
