# Generated by Django 4.2.1 on 2024-03-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
    ]
